# Generated by Django 3.2.5 on 2022-03-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.IntegerField()),
                ('date', models.DateField()),
                ('hora', models.TimeField()),
                ('lat_origin', models.IntegerField()),
                ('lng_origin', models.IntegerField()),
                ('lat_destination', models.IntegerField()),
                ('lng_destination', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
